datastore:
  connection-string: postgresql://airflow:airflow@postgres:5432/hh_vacancies

vacancy-limit: 250
vacancy-prefetch: 50
hh-api-endpoint: "https://api.hh.ru/vacancies"
request-timeout-in-seconds: 15